"""poll customization

Revision ID: dabf1a300995
Revises: 3f6e36ee74c3
Create Date: 2018-04-26 17:08:53.424212

"""
from alembic import op
import sqlalchemy as sa

import flaskbb


# revision identifiers, used by Alembic.
revision = 'dabf1a300995'
down_revision = '3f6e36ee74c3'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls_polls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('changing_votes_allowed', sa.Boolean(), nullable=False, default=False))
        batch_op.add_column(sa.Column('closes', flaskbb.utils.database.UTCDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('max_votes_allowed', sa.Integer(), nullable=False, default=999))
        batch_op.add_column(sa.Column('result_visible_before_closed', sa.Boolean(), nullable=False, default=True))
        batch_op.add_column(sa.Column('result_visible_before_voting', sa.Boolean(), nullable=False, default=False))
        batch_op.add_column(sa.Column('votes_public', sa.Boolean(), nullable=False, default=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls_polls', schema=None) as batch_op:
        batch_op.drop_column('votes_public')
        batch_op.drop_column('result_visible_before_voting')
        batch_op.drop_column('result_visible_before_closed')
        batch_op.drop_column('max_votes_allowed')
        batch_op.drop_column('closes')
        batch_op.drop_column('changing_votes_allowed')

    # ### end Alembic commands ###
